FROM node:18 AS development

WORKDIR /jio_loyalty/src/app

COPY package*.json ./

RUN npm install

RUN npm install --save @nestjs/typeorm typeorm

RUN npm install pg --save

COPY . .

RUN npm run build

# CMD [ "npm", "run", "start:dev" ]