FROM node:18 as development

WORKDIR /app

COPY package*.json ./

RUN npm install && npm i @nestjs/cli --save && npm i --save @nestjs/typeorm typeorm && npm install pg --save && npm install class-validator --save

COPY . .

RUN npm run build
