FROM node:18-alpine AS development

# Create app directory in the user's home directory
RUN mkdir -p /home/node/app

# Create app directory
WORKDIR /home/node/app

# Copy application dependency manifests to the container image.
# A wildcard is used to ensure copying both package.json AND package-lock.json (when available).
# Copying this first prevents re-running npm install on every code change.
COPY --chown=node:node package*.json ./

# Remove the node_modules directory to ensure it gets recreated with correct permissions
RUN rm -rf node_modules

# Install app dependencies using the `npm ci` command instead of `npm install`
RUN npm ci \
    && npm install --save @nestjs/typeorm typeorm \
    && npm install pg --save \
    && chown -R node:node /home/node

# Set appropriate permissions for the app directory
RUN chown -R node:node /home/node

# Bundle app source
COPY --chown=node:node . .

# Use the node user from the image (instead of the root user)
RUN mkdir ./dist
RUN chown -R node:node ./dist
RUN chmod 777 ./dist
# CMD [ "npm", "run", "start:dev" ]
